const mongoose = require('mongoose');

const boardSchema = new mongoose.Schema({
  _id: { type: String, required: true }, // Using String to accept UUIDs generated by the offline Flutter client
  title: { type: String, required: true },
  color: { type: String, default: '#3B82F6' }, // From the UI design requirements
  ownerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  isDeleted: { type: Boolean, default: false },
  updatedAt: { type: Date, required: true }, // Explicitly defined to sync with Flutter's UTC time
  createdAt: { type: Date, required: true }
});

module.exports = mongoose.model('Board', boardSchema);